// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeletePost(ctx context.Context, id int32) error
	FindPostByID(ctx context.Context, id int32) (Post, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int32) (User, error)
	ListPostsByUserID(ctx context.Context, userID int32) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
